// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqdWcMYs8vcSseA9CpsimBdw0yuWxKz4g',
    appId: '1:740433575933:web:87866d0fa2be8b905ea394',
    messagingSenderId: '740433575933',
    projectId: 'message-app-b01a4',
    authDomain: 'message-app-b01a4.firebaseapp.com',
    storageBucket: 'message-app-b01a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKT79SG_mfVrd-z2roFeYqXjFcn1B6jAg',
    appId: '1:740433575933:android:39dc3b6859c418df5ea394',
    messagingSenderId: '740433575933',
    projectId: 'message-app-b01a4',
    storageBucket: 'message-app-b01a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM2jAcJzmXZnzXjQQaTp8vMGoFae3ErE0',
    appId: '1:740433575933:ios:69f304d11876c8885ea394',
    messagingSenderId: '740433575933',
    projectId: 'message-app-b01a4',
    storageBucket: 'message-app-b01a4.appspot.com',
    iosClientId: '740433575933-2hb48ihs0vnpq1ia90sno39g8iknvu5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM2jAcJzmXZnzXjQQaTp8vMGoFae3ErE0',
    appId: '1:740433575933:ios:050c9807968778245ea394',
    messagingSenderId: '740433575933',
    projectId: 'message-app-b01a4',
    storageBucket: 'message-app-b01a4.appspot.com',
    iosClientId: '740433575933-g9if8m4voqhqpav12hh1jk89p6tu9055.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp.RunnerTests',
  );
}
